### ISSUE TITLE
 custom_lint not working

### ISSUE THREAD

**Issue by Ayush0Chaudhary** [invertase/dart_custom_lint#139] opened 2023-04-06 17:44 UTC
**Describe the bug**
custom_lint not working

**Error**
```
The Dart VM service is listening on http://127.0.0.1:40133/-q-_BXrGcU0=/
The Dart DevTools debugger and profiler is available at: http://127.0.0.1:40133/-q-_BXrGcU0=/devtools/#/?uri=ws%3A%2F%2F127.0.0.1%3A40133%2F-q-_BXrGcU0%3D%2Fws
Failed to start pluginsThe request analysis.setContextRoots failed with the following error:
RequestErrorCode.PLUGIN_ERROR
Bad state: Failed to start the plugins.
at:
#0      _SocketCustomLintServerToClientChannel._checkInitializationFail.<anonymous closure> (package:custom_lint/src/v2/server_to_client_channel.dart:490:11)
#1      _rootRunUnary (dart:async/zone.dart:1406:47)
#2      _CustomZone.runUnary (dart:async/zone.dart:1307:19)
<asynchronous suspension>
#3      Future.any.onValue (dart:async/future.dart:612:5)
<asynchronous suspension>

The request plugin.shutdown failed with the following error:
RequestErrorCode.PLUGIN_ERROR
PathNotFoundException: Deletion failed, path = '/tmp/DGUMMV' (OS Error: No such file or directory, errno = 2)
at:
#0      _checkForErrorResponse (dart:io/common.dart:42:9)
#1      _Directory._delete.<anonymous closure> (dart:io/directory_impl.dart:185:7)
#2      _rootRunUnary (dart:async/zone.dart:1406:47)
#3      _CustomZone.runUnary (dart:async/zone.dart:1307:19)
<asynchronous suspension>
#4      Future.wait.<anonymous closure> (dart:async/future.dart:522:21)
<asynchronous suspension>
#5      _SocketCustomLintServerToClientChannel.close (package:custom_lint/src/v2/server_to_client_channel.dart:500:5)
<asynchronous suspension>
#6      CustomLintServer._handlePluginShutdown (package:custom_lint/src/v2/custom_lint_analyzer_plugin.dart:227:5)
<asynchronous suspension>
#7      CustomLintServer._handleRequest.<anonymous closure> (package:custom_lint/src/v2/custom_lint_analyzer_plugin.dart:129:13)
<asynchronous suspension>
#8      CustomLintServer._handleRequest (package:custom_lint/src/v2/custom_lint_analyzer_plugin.dart:124:22)
<asynchronous suspension>


```

**To Reproduce**
`flutter run custom_lint`

**Expected behavior**
it should work ig

**Comment by Ayush0Chaudhary** [comment] 2023-04-06 17:45
@rrousselGit can you help me with the problem?

**Comment by Ayush0Chaudhary** [comment] 2023-04-06 17:45
I also attched the error message

**Comment by rrousselGit** [comment] 2023-04-06 17:54
Sounds like a duplicate of https://github.com/invertase/dart_custom_lint/issues/115

**Comment by Ayush0Chaudhary** [comment] 2023-04-06 17:55
Ok I'll try that solution 🫡

**Comment by rrousselGit** [comment] 2023-04-13 10:59
Closing as duplicate of #115

**Closed by rrousselGit** 2023-04-13 10:59 UTC
Labels: bug
