### ISSUE TITLE
Run all fixes via command line

### ISSUE THREAD

**Issue by ju851zel** [invertase/dart_custom_lint#83] opened 2023-02-18 18:26 UTC
It would be nice to have the command line fix all the problems where a fix exists.
Like `dart fix --apply`.

Maybe something like this already exists and I couldn't find it.

**Comment by rrousselGit** [comment] 2023-02-18 20:23
Duplicate of https://github.com/invertase/dart_custom_lint/issues/57

It's not simple, as custom_lint doesn't quite know how to apply fixes. And especially not how to apply multiple fixes at once.

**Closed by rrousselGit** 2023-02-18 20:23 UTC
Labels: enhancement
