### ISSUE TITLE
Error when running/installing custom_lint on Windows 11

### ISSUE THREAD

**Issue by damywise** [invertase/dart_custom_lint#100] opened 2023-03-01 02:16 UTC
**Describe the bug**
Just error when running/installing
logs:
```sj
Failed to start pluginsThe request analysis.setContextRoots failed with the following error:
RequestErrorCode.PLUGIN_ERROR
Bad state: Failed to start the plugins.
at:
#0      _SocketCustomLintServerToClientChannel._checkInitializationFail.<anonymous closure> (package:custom_lint/src/v2/server_to_client_channel.dart:490:11)
#1      _rootRunUnary (dart:async/zone.dart:1406:47)
#2      _CustomZone.runUnary (dart:async/zone.dart:1307:19)
<asynchronous suspension>
#3      Future.any.onValue (dart:async/future.dart:612:5)
<asynchronous suspension>
```

**To Reproduce**

Add `custom_lint` to project
`dart run custom_lint`

**Expected behavior**
Working

**Comment by rrousselGit** [comment] 2023-03-01 07:01
Could you share the full log file?

Could you also make a github repository to reproduce the problem?

**Comment by damywise** [comment] 2023-03-01 07:19
That's the full log file (`custom_lint.log`)

**Comment by damywise** [comment] 2023-03-01 07:24
https://github.com/damywise/untitled1

**Comment by AhmedLSayed9** [comment] 2023-03-04 04:12
@damywise 
You forgot to wrap your `runApp` with a `ProviderScope` widget.

As `riverpod_lint ` docs says: `Custom lint rules created by riverpod_lint may not show-up in dart analyze. To fix this, you can run a custom command line: custom_lint`

so by running `dart run custom_lint` you should get a lint about missing a ProviderScope.

**Comment by damywise** [comment] 2023-03-04 10:36
Sorry but that's not the problem I encountered.
My problem is that I can't run `dart run custom_lint` at all

**Comment by CATAV009** [comment] 2023-03-06 18:10
I'm getting the same error when running `flutter pub run custom_lint` in my CI using the `cirrusci/flutter:stable` image

**Comment by damywise** [comment] 2023-03-06 23:40
Interesting, there might be a similar problem with my firewall then. I'll check later.

**Comment by sukwony** [comment] 2023-03-07 02:08
I'm facing the same issue, logfile content is also same

Failed to start pluginsThe request analysis.setContextRoots failed with the following error:
RequestErrorCode.PLUGIN_ERROR
Bad state: Failed to start the plugins.
at:
#0      _SocketCustomLintServerToClientChannel._checkInitializationFail.<anonymous closure> (package:custom_lint/src/v2/server_to_client_channel.dart:490:11)
#1      _rootRunUnary (dart:async/zone.dart:1406:47)
#2      _CustomZone.runUnary (dart:async/zone.dart:1307:19)
<asynchronous suspension>
#3      Future.any.onValue (dart:async/future.dart:612:5)
<asynchronous suspension>

**Comment by damywise** [comment] 2023-03-07 02:25
I checked. I don't think there's any problem with my firewall, so still no info on why.

**Comment by rrousselGit** [comment] 2023-03-08 19:53
> https://github.com/damywise/untitled1

@damywise Your repository isn't correctly setup. You did:

```yaml
linter:
  analyzer:
    plugins:
      - custom_lint
  rules:
  ...
```

Instead of:

```yaml
analyzer:
  plugins:
    - custom_lint
linter:
  rules:
  ...
```


custom_lint isn't even starting in your repo for me. And it's working fine after fixing it

**Comment by damywise** [comment] 2023-03-08 21:44
Oh yeah sorry about that, but I used the correct setup on my actual project and it's not starting either.

**Comment by rrousselGit** [comment] 2023-03-09 05:49
One thing that needs clear-up:

Is this specific to the command line? Or do you folks also face this error when viewing your project in the IDE?

**Comment by CATAV009** [comment] 2023-03-09 05:58
@rrousselGit In my case it only fails when it runs in my [Docker CI](https://github.com/CATAV009/custom_lint_problem/blob/main/.github/workflows/analyze.yaml) . In my local environment I run the command and it works. It works in my IDE as well.

**Comment by rrousselGit** [comment] 2023-03-09 06:16
@CATAV009 I'm not sure if your case is the same as the others though. Your case seems more like a race condition where the OS takes the port first.

I'll publish a new version that updates the error message with more information.

**Comment by rrousselGit** [comment] 2023-03-09 06:23
The weird thing is, @damywise doesn't seem to have any extra logs besides "Failed to start".

There's no stderr of the process present in the log file. As opposed to you @CATAV009 who has `Could not start the VM service: localhost:40387 is already in use.` before the error, which is the reason why the process failed to start.

**Comment by rrousselGit** [comment] 2023-03-09 06:34
The "port already in use" error was caused by some redundant code. I've removed it and it's gone now.
I don't think that's the problem others face though.

**Comment by damywise** [comment] 2023-03-09 07:13
> Is this specific to the command line? Or do you folks also face this error when viewing your project in the IDE?
Oh yeah it also fails on Android Studio

**Comment by rrousselGit** [comment] 2023-03-09 07:30
I've published a new version that fixes the port issue. Could you try that? Although I doubt that's your problem sadly

**Comment by rrousselGit** [comment] 2023-03-09 08:17
Welp looks like the vm-service port isn't actually randomized and only tries 8181

Let me see if I can disable vm-services in release mode.

**Comment by damywise** [comment] 2023-03-09 11:47
> I've published a new version that fixes the port issue. Could you try that? Although I doubt that's your problem sadly

Nah still not working

**Comment by rrousselGit** [comment] 2023-03-13 10:22
@DarkHeros09 Your issue appears unrelated as that's a completely different message.

**Comment by rrousselGit** [comment] 2023-03-13 12:34
I just tried it on a windows machine and unfortunately, it all works fine for me.

**Comment by rrousselGit** [comment] 2023-03-18 09:33
Closing in favour of https://github.com/invertase/dart_custom_lint/issues/115

**Closed by rrousselGit** 2023-03-18 09:33 UTC
Labels: bug, question
