### ISSUE TITLE
Custom Lint expects pubspec in the wrong directory

### ISSUE THREAD

**Issue by dario-digregorio** [invertase/dart_custom_lint#174] opened 2023-07-23 09:15 UTC
Hi Remi :)

**Describe the bug**
Custom Lints won't work. I can see following error in the logs which shows that custom lints expects pubspec inside my firebase function folder:
```
[custom_lint client] 2023-07-23T11:04:27.309669 PathNotFoundException: Cannot open file, path = '/Users/dario/development/yawa/firebase/functions/pubspec.yaml' (OS Error: No such file or directory, errno = 2)
[custom_lint client] 2023-07-23T11:04:27.309669 #0      _checkForErrorResponse (dart:io/common.dart:55:9)
[custom_lint client] 2023-07-23T11:04:27.309669 #1      _File.open.<anonymous closure> (dart:io/file_impl.dart:381:7)
[custom_lint client] 2023-07-23T11:04:27.309669 #2      _rootRunUnary (dart:async/zone.dart:1407:47)
[custom_lint client] 2023-07-23T11:04:27.309669 #3      _CustomZone.runUnary (dart:async/zone.dart:1308:19)
[custom_lint client] 2023-07-23T11:04:27.309669 <asynchronous suspension>
[custom_lint client] 2023-07-23T11:04:27.309669 #4      _File.readAsString (dart:io/file_impl.dart:621:18)
[custom_lint client] 2023-07-23T11:04:27.309669 <asynchronous suspension>
[custom_lint client] 2023-07-23T11:04:27.309669 #5      parsePubspec (package:custom_lint/src/package_utils.dart:81:24)
[custom_lint client] 2023-07-23T11:04:27.309669 <asynchronous suspension>
[custom_lint client] 2023-07-23T11:04:27.309669
```
I am using a M1 Macbook. On my Windows PC it works as expected.

**To Reproduce**
Not sure how. I couldn’t find a way to change the path it searches for pubspec. But all files are at the project root.

**Expected behavior**
That the right path for pubspec is choosen and Custom Lints work.

**Comment by rrousselGit** [comment] 2023-07-24 09:36
Closing as duplicate of https://github.com/invertase/dart_custom_lint/issues/148

**Closed by rrousselGit** 2023-07-24 09:36 UTC
Labels: bug

**Comment by rrousselGit** [comment] 2023-07-24 16:11
Unless you give a way to reproduce the issue, there's not much I can do anyway. I can only assume that this is the same issue as with https://github.com/invertase/dart_custom_lint/issues/148 and cannot work on this
